### ISSUE TITLE
Convert to scripts & include Makefile 

### ISSUE THREAD

**Issue by nicolebid** [MoNorouzi23/Airbnb_analysis#15]
Scripts to include

- [x] eda plots
- [x] data cleaning & feature engineering
- [x] transformations &  data splitting 
- [x] models
- [x] hyperparameter optimization
- [x] rfecv model 
- [x] feature importances
- [x] model evaluation (training & cv) 
- [x] shap values

**Comment by karan-khubdikar** [comment]
Thanks Nicole for breaking down the report into scripts!
